/*
** EPITECH PROJECT, 2020
** project
** File description:
** function
*/

#ifndef REF_SYSCALL_SND_
#define REF_SYSCALL_SND_

#include <stddef.h>
#include "ref_syscall.h"

const static struct ref_syscall ref_syscall_snd[435] = {
    {"read", {INT, STRING, INT}, 3},
    {"write", {INT, STRING, INT}, 3},
    {"open", {STRING, FLAG, INT}, 3},
    {"close", {INT}, 1},
    {"stat", {STRING, STRUCT}, 2},
    {"fstat", {INT, STRUCT}, 2},
    {"lstat", {STRING, STRUCT}, 2},
    {"poll", {STRUCT, INT, INT}, 3},
    {"lseek", {INT, STRUCT, INT}, 3},
    {"mmap", {ADDR, INT, INT, FLAG, INT, INT}, 6},
    {"mprotect", {INT, INT, INT}, 3},
    {"munmap", {ADDR, INT}, 2},
    {"brk", {ADDR}, 1},
    {"rt_sigaction", {INT, STRUCT, STRUCT, INT}, 4},
    {"rt_sigprocmask", {FLAG, STRUCT, STRUCT, INT}, 4},
    {"rt_sigreturn", {INT}, 1},
    {"ioctl", {INT, INT, INT}, 3},
    {"pread64", {INT, STRING, INT, STRUCT}, 4},
    {"pwrite64", {INT, STRING, INT, STRUCT}, 4},
    {"readv", {INT, STRUCT, INT}, 3},
    {"writev", {INT, STRUCT, INT}, 3},
    {"access", {STRING, INT}, 2},
    {"pipe", {ARRAY | INT}, 1},
    {"select", {INT, ADDR, ADDR, ADDR, STRUCT}, 5},
    {"sched_yield", {0, 0}, 0},
    {"mremap", {ADDR, INT, INT, FLAG, ADDR}, 5},
    {"msync", {INT, INT, FLAG}, 3},
    {"mincore", {INT, INT, STRING}, 3},
    {"madvise", {INT, INT, INT}, 3},
    {"shmget", {STRUCT, INT, INT}, 3},
    {"shmat", {INT, STRING, INT}, 3},
    {"shmctl", {INT, INT, STRUCT}, 3},
    {"dup", {INT}, 1},
    {"dup2", {INT, INT}, 2},
    {"pause", {}, 0},
    {"nanosleep", {STRUCT, STRUCT}, 2},
    {"getitimer", {INT, STRUCT}, 2},
    {"alarm", {INT}, 1},
    {"setitimer", {INT, STRUCT, STRUCT}, 3},
    {"getpid", {}, 0},
    {"sendfile", {INT, INT, STRUCT, INT}, 4},
    {"socket", {INT, INT, INT}, 3},
    {"connect", {INT, STRUCT, INT}, 3},
    {"accept", {INT, STRUCT, ADDR}, 3},
    {"sendto", {INT, ADDR, INT, FLAG, STRUCT, INT}, 6},
    {"recvfrom", {INT, ADDR, INT, FLAG, STRUCT, ADDR}, 6},
    {"sendmsg", {INT, STRUCT, FLAG}, 3},
    {"recvmsg", {INT, STRUCT, FLAG}, 3},
    {"shutdown", {INT, FLAG}, 2},
    {"bind", {INT, STRUCT, INT}, 3},
    {"listen", {INT, INT}, 2},
    {"getsockname", {INT, STRUCT, ADDR}, 3},
    {"getpeername", {INT, STRUCT, ADDR}, 3},
    {"socketpair", {INT, INT, INT, ADDR}, 4},
    {"setsockopt", {INT, INT, INT, STRING, INT}, 5},
    {"getsockopt", {INT, INT, INT, STRING, ADDR}, 5},
    {"clone", {FLAG, INT, STRUCT, STRUCT, INT}, 5},
    {"fork", {}, 0},
    {"vfork", {}, 0},
    {"execve", {STRING, ARRAY | STRING, ARRAY | STRING}, 3},
    {"exit", {INT}, 1},
    {"wait4", {INT, ADDR, INT, STRUCT}, 4},
    {"kill", {INT, INT}, 2},
    {"uname", {STRUCT}, 1},
    {"semget", {STRUCT, INT, INT}, 3},
    {"semop", {INT, STRUCT, INT}, 3},
    {"semctl", {INT, INT, INT, UNDEFINED}, 4},
    {"shmdt", {STRING}, 1},
    {"msgget", {STRUCT, INT}, 2},
    {"msgsnd", {INT, STRUCT, INT, INT}, 4},
    {"msgrcv", {INT, STRUCT, INT, INT, INT}, 5},
    {"msgctl", {INT, INT, STRUCT}, 3},
    {"fcntl", {INT, INT, INT}, 3},
    {"flock", {INT, INT}, 2},
    {"fsync", {INT}, 1},
    {"fdatasync", {INT}, 1},
    {"truncate", {STRING, INT}, 2},
    {"ftruncate", {INT, INT}, 2},
    {"getdents", {INT, STRUCT, INT}, 3},
    {"getcwd", {STRING, INT}, 2},
    {"chdir", {STRING}, 1},
    {"fchdir", {INT}, 1},
    {"rename", {STRING, STRING}, 2},
    {"mkdir", {STRING, INT}, 2},
    {"rmdir", {STRING}, 1},
    {"creat", {STRING, INT}, 2},
    {"link", {STRING, STRING}, 2},
    {"unlink", {STRING}, 1},
    {"symlink", {STRING, STRING}, 2},
    {"readlink", {STRING, STRING, INT}, 3},
    {"chmod", {STRING, STRUCT}, 2},
    {"fchmod", {INT, STRUCT}, 2},
    {"chown", {STRING, INT, INT}, 3},
    {"fchown", {INT, INT, INT}, 3},
    {"lchown", {STRING, INT, INT}, 3},
    {"umask", {INT}, 1},
    {"gettimeofday", {STRUCT, STRUCT}, 2},
    {"getrlimit", {INT, STRUCT}, 2},
    {"getrusage", {INT, STRUCT}, 2},
    {"sysinfo", {STRUCT}, 1},
    {"times", {STRUCT}, 1},
    {"ptrace", {INT, INT, ADDR, ADDR}, 4},
    {"getuid", {}, 0},
    {"syslog", {INT, STRING, INT}, 3},
    {"getgid", {}, 0},
    {"setuid", {INT}, 1},
    {"setgid", {INT}, 1},
    {"geteuid", {}, 0},
    {"getegid", {}, 0},
    {"setpgid", {INT, INT}, 2},
    {"getppid", {}, 0},
    {"getpgrp", {}, 0},
    {"setsid", {}, 0},
    {"setreuid", {INT, INT}, 2},
    {"setregid", {INT, INT}, 2},
    {"getgroups", {INT, ADDR}, 2},
    {"setgroups", {INT, ADDR}, 2},
    {"setresuid", {ADDR, ADDR, ADDR}, 3},
    {"getresuid", {ADDR, ADDR, ADDR}, 3},
    {"setresgid", {INT, INT, INT}, 3},
    {"getresgid", {ADDR, ADDR, ADDR}, 3},
    {"getpgid", {INT}, 1},
    {"setfsuid", {INT}, 1},
    {"setfsgid", {INT}, 1},
    {"getsid", {INT}, 1},
    {"capget", {STRUCT, STRUCT}, 2},
    {"capset", {STRUCT, STRUCT}, 2},
    {"rt_sigpending", {STRUCT, INT}, 2},
    {"rt_sigtimedwait", {STRUCT, STRUCT, STRUCT, INT}, 4},
    {"rt_sigqueueinfo", {INT, INT, STRUCT}, 3},
    {"rt_sigsuspend", {STRUCT, INT}, 2},
    {"sigaltstack", {STRUCT, STRUCT}, 2},
    {"utime", {STRING, STRUCT}, 2},
    {"mknod", {STRING, STRUCT, INT}, 3},
    {"uselib", {UNDEFINED}, 1},
    {"personality", {INT}, 1},
    {"ustat", {INT, STRUCT}, 2},
    {"statfs", {STRING, STRUCT}, 2},
    {"fstatfs", {INT, STRUCT}, 2},
    {"sysfs", {INT, INT, INT}, 3},
    {"getpriority", {INT, INT}, 2},
    {"setpriority", {INT, INT, INT}, 3},
    {"sched_setparam", {INT, STRUCT}, 2},
    {"sched_getparam", {INT, STRUCT}, 2},
    {"sched_setscheduler", {INT, INT, STRUCT}, 3},
    {"sched_getscheduler", {INT}, 1},
    {"sched_get_priority_max", {INT}, 1},
    {"sched_get_priority_min", {INT}, 1},
    {"sched_rr_get_interval", {INT, STRUCT}, 2},
    {"mlock", {INT, INT}, 2},
    {"munlock", {INT, INT}, 2},
    {"mlockall", {FLAG}, 1},
    {"munlockall", {}, 0},
    {"vhangup", {}, 0},
    {"modify_ldt", {INT, ADDR, INT}, 3},
    {"pivot_root", {STRING, STRING}, 2},
    {"_sysctl", {STRUCT}, 1},
    {"prctl", {INT, INT, INT, INT}, 4},
    {"arch_prctl", {STRUCT, INT, ADDR}, 3},
    {"adjtimex", {STRUCT}, 1},
    {"setrlimit", {INT, STRUCT}, 2},
    {"chroot", {STRING}, 1},
    {"sync", {}, 0},
    {"acct", {STRING}, 1},
    {"settimeofday", {STRUCT, STRUCT}, 2},
    {"mount", {STRING, STRING, STRING, FLAG, ADDR}, 5},
    {"umount2", {STRING, FLAG}, 2},
    {"swapon", {STRING, FLAG}, 2},
    {"swapoff", {STRING}, 1},
    {"reboot", {INT, INT, INT, ADDR}, 4},
    {"sethostname", {STRING, INT}, 2},
    {"setdomainname", {STRING, INT}, 2},
    {"iopl", {INT, STRUCT}, 2},
    {"ioperm", {INT, INT, INT}, 3},
    {"create_module", {UNDEFINED}, 1},
    {"init_module", {ADDR, INT, STRING}, 3},
    {"delete_module", {ADDR, FLAG}, 2},
    {"get_kernel_syms", {UNDEFINED}, 1},
    {"query_module", {UNDEFINED}, 1},
    {"quotactl", {INT, STRING, STRUCT, ADDR}, 4},
    {"nfsservctl", {UNDEFINED}, 1},
    {"getpmsg", {UNDEFINED}, 1},
    {"putpmsg", {UNDEFINED}, 1},
    {"afs_syscall", {UNDEFINED}, 1},
    {"tuxcall", {UNDEFINED}, 1},
    {"security", {UNDEFINED}, 1},
    {"gettid", {}, 0},
    {"readahead", {INT, STRUCT, INT}, 3},
    {"setxattr", {STRING, STRING, ADDR, INT, FLAG}, 5},
    {"lsetxattr", {STRING, STRING, ADDR, INT, FLAG}, 5},
    {"fsetxattr", {INT, STRING, ADDR, INT, FLAG}, 5},
    {"getxattr", {STRING, STRING, ADDR, INT}, 4},
    {"lgetxattr", {STRING, STRING, ADDR, INT}, 4},
    {"fgetxattr", {INT, ADDR, ADDR, INT}, 4},
    {"listxattr", {STRING, STRING, INT}, 3},
    {"llistxattr", {STRING, STRING, INT}, 3},
    {"flistxattr", {INT, STRING, INT}, 3},
    {"removexattr", {STRING, STRING}, 2},
    {"lremovexattr", {STRING, STRING}, 2},
    {"fremovexattr", {INT, STRING}, 2},
    {"tkill", {INT, UNDEFINED}, 2},
    {"time", {STRUCT}, 1},
    {"futex", {ADDR, INT, UNDEFINED, STRUCT, ADDR, UNDEFINED}, 6},
    {"sched_setaffinity", {INT, INT, ADDR}, 3},
    {"sched_getaffinity", {INT, INT, ADDR}, 3},
    {"set_thread_area", {UNDEFINED}, 1},
    {"io_setup", {INT, STRUCT}, 2},
    {"io_destroy", {STRUCT}, 1},
    {"io_getevents", {STRUCT, INT, INT, STRUCT}, 4},
    {"io_submit", {STRUCT, INT, STRUCT}, 3},
    {"io_cancel", {STRUCT, STRUCT, STRUCT}, 3},
    {"get_thread_area", {UNDEFINED}, 1},
    {"lookup_dcookie", {UNDEFINED, INT, INT}, 3},
    {"epoll_create", {INT}, 1},
    {"epoll_ctl_old", {UNDEFINED}, 1},
    {"epoll_wait_old", {UNDEFINED}, 1},
    {"remap_file_pages", {INT, INT, INT, INT, FLAG}, 5},
    {"getdents64", {INT, STRUCT, INT}, 3},
    {"set_tid_address", {ADDR}, 1},
    {"restart_syscall", {}, 0},
    {"semtimedop", {INT, STRUCT, INT, STRUCT}, 4},
    {"fadvise64", {INT, STRUCT, INT, INT}, 4},
    {"timer_create", {STRUCT, STRUCT, STRUCT}, 3},
    {"timer_settime", {STRUCT, FLAG, STRUCT, STRUCT}, 4},
    {"timer_gettime", {STRUCT, STRUCT}, 2},
    {"timer_getoverrun", {STRUCT}, 1},
    {"timer_delete", {STRUCT}, 1},
    {"clock_settime", {STRUCT, STRUCT}, 2},
    {"clock_gettime", {STRUCT, STRUCT}, 2},
    {"clock_getres", {STRUCT, STRUCT}, 2},
    {"clock_nanosleep", {STRUCT, FLAG, STRUCT, STRUCT}, 4},
    {"exit_group", {INT}, 1},
    {"epoll_wait", {INT, STRUCT, INT, INT}, 4},
    {"epoll_ctl", {INT, INT, INT, STRUCT}, 4},
    {"tgkill", {INT, INT, INT}, 3},
    {"utimes", {STRING, STRUCT}, 2},
    {"vserver", {UNDEFINED}, 1},
    {"mbind", {INT, INT, INT, ADDR, INT, FLAG}, 6},
    {"set_mempolicy", {INT, ADDR, INT}, 3},
    {"get_mempolicy", {ADDR, ADDR, INT, ADDR, FLAG}, 5},
    {"mq_open", {STRING, FLAG, STRUCT, STRUCT}, 4},
    {"mq_unlink", {STRING}, 1},
    {"mq_timedsend", {STRUCT, STRING, INT, INT, STRUCT}, 5},
    {"mq_timedreceive", {STRUCT, STRING, INT, ADDR, STRUCT}, 5},
    {"mq_notify", {STRUCT, STRUCT}, 2},
    {"mq_getsetattr", {STRUCT, STRUCT, STRUCT}, 3},
    {"kexec_load", {INT, INT, STRUCT, FLAG}, 4},
    {"waitid", {INT, INT, STRUCT, INT, STRUCT}, 5},
    {"add_key", {STRUCT, STRING, ADDR, INT}, 4},
    {"request_key", {STRUCT, STRING, STRING, STRUCT}, 4},
    {"keyctl", {INT, INT, INT, INT, INT}, 5},
    {"ioprio_set", {INT, INT, INT}, 3},
    {"ioprio_get", {INT, INT}, 2},
    {"inotify_init", {}, 0},
    {"inotify_add_watch", {INT, STRING, UNDEFINED}, 3},
    {"inotify_rm_watch", {INT, UNDEFINED}, 2},
    {"migrate_pages", {INT, INT, ADDR, ADDR}, 4},
    {"openat", {INT, STRING, FLAG, INT}, 4},
    {"mkdirat", {INT, STRING, INT}, 3},
    {"mknodat", {INT, STRING, INT, INT}, 4},
    {"fchownat", {INT, STRING, INT, INT, FLAG}, 5},
    {"futimesat", {INT, STRING, STRUCT}, 3},
    {"newfstatat", {INT, STRING, STRUCT, FLAG}, 4},
    {"unlinkat", {INT, STRING, FLAG}, 3},
    {"renameat", {INT, STRING, INT, STRING}, 4},
    {"linkat", {INT, STRING, INT, STRING, FLAG}, 5},
    {"symlinkat", {STRING, INT, STRING}, 3},
    {"readlinkat", {INT, STRING, STRING, INT}, 4},
    {"fchmodat", {INT, STRING, STRUCT}, 3},
    {"faccessat", {INT, STRING, INT}, 3},
    {"pselect6", {INT, ADDR, ADDR, ADDR, STRUCT, ADDR}, 6},
    {"ppoll", {STRUCT, INT, STRUCT, STRUCT, INT}, 5},
    {"unshare", {FLAG}, 1},
    {"set_robust_list", {STRUCT, INT}, 2},
    {"get_robust_list", {INT, STRUCT, ADDR}, 3},
    {"splice", {INT, STRUCT, INT, STRUCT, INT, FLAG}, 6},
    {"tee", {INT, INT, INT, FLAG}, 4},
    {"sync_file_range", {INT, STRUCT, STRUCT, FLAG}, 4},
    {"vmsplice", {INT, STRUCT, INT, FLAG}, 4},
    {"move_pages", {INT, INT, ADDR, ADDR, ADDR, FLAG}, 6},
    {"utimensat", {INT, STRING, STRUCT, FLAG}, 4},
    {"epoll_pwait", {INT, STRUCT, INT, INT, STRUCT, INT}, 6},
    {"signalfd", {INT, STRUCT, INT}, 3},
    {"timerfd_create", {INT, FLAG}, 2},
    {"eventfd", {INT}, 1},
    {"fallocate", {INT, INT, STRUCT, STRUCT}, 4},
    {"timerfd_settime", {INT, FLAG, STRUCT, STRUCT}, 4},
    {"timerfd_gettime", {INT, STRUCT}, 2},
    {"accept4", {INT, STRUCT, ADDR, FLAG}, 4},
    {"signalfd4", {INT, STRUCT, INT, FLAG}, 4},
    {"eventfd2", {INT, FLAG}, 2},
    {"epoll_create1", {FLAG}, 1},
    {"dup3", {INT, INT, FLAG}, 3},
    {"pipe2", {ADDR, FLAG}, 2},
    {"inotify_init1", {FLAG}, 1},
    {"preadv", {INT, STRUCT, INT, INT, INT}, 5},
    {"pwritev", {INT, STRUCT, INT, INT, INT}, 5},
    {"rt_tgsigqueueinfo", {INT, INT, INT, STRUCT}, 4},
    {"perf_event_open", {STRUCT, INT, INT, INT, FLAG}, 5},
    {"recvmmsg", {INT, STRUCT, INT, FLAG, STRUCT}, 5},
    {"fanotify_init", {FLAG, FLAG}, 2},
    {"fanotify_mark", {INT, FLAG, UNDEFINED, INT, INT}, 5},
    {"prlimit64", {INT, INT, STRUCT, STRUCT}, 4},
    {"name_to_handle_at", {INT, STRING, STRUCT, ADDR, FLAG}, 5},
    {"open_by_handle_at", {INT, STRING, STRUCT, ADDR, FLAG}, 5},
    {"clock_adjtime", {STRUCT, STRUCT}, 2},
    {"syncfs", {INT}, 1},
    {"sendmmsg", {INT, STRUCT, INT, FLAG}, 4},
    {"setns", {INT, INT}, 2},
    {"getcpu", {ADDR, ADDR, STRUCT}, 3},
    {"process_vm_readv", {INT, STRUCT, INT, STRUCT, INT, FLAG}, 6},
    {"process_vm_writev", {INT, STRUCT, INT, STRUCT, INT, FLAG}, 6},
    {"kcmp", {INT, INT, INT, INT, INT}, 5},
    {"finit_module", {INT, STRING, FLAG}, 3},
    {"sched_setattr", {INT, STRUCT, FLAG}, 3},
    {"sched_getattr", {INT, STRUCT, INT, FLAG}, 4},
    {"renameat2", {INT, STRING, INT, STRING, FLAG}, 5},
    {"seccomp", {INT, FLAG, STRING}, 3},
    {"getrandom", {STRING, INT, FLAG}, 3},
    {"memfd_create", {STRING, FLAG}, 2},
    {"kexec_file_load", {INT, INT, INT, STRING, FLAG}, 5},
    {"bpf", {INT, ADDR, INT}, 3},
    {"stub_execveat", {INT, STRING, STRING, STRING, FLAG}, 5},
    {"userfaultfd", {FLAG}, 1},
    {"membarrier", {INT, FLAG}, 2},
    {"mlock2", {INT, INT, FLAG}, 3},
    {"copy_file_range", {INT, STRUCT, INT, STRUCT, INT, FLAG}, 6},
    {"preadv2", {INT, STRUCT, INT, INT, INT, FLAG}, 6},
    {"pwritev2", {INT, STRUCT, INT, INT, INT, FLAG}, 6},
    {"pkey_mprotect", {}, 0},
    {"pkey_alloc", {}, 0},
    {"pkey_free", {}, 0},
    {"statx", {}, 0},
    {"io_pgetevents", {}, 0},
    {"rseq", {}, 0},
    {"pkey_mprotect", {}, 0},
    {"undefined", {}, 0},
    {"undefined", {}, 0}
};

#endif
